// Argus Cyclist - Virtual Cycling Environment for interactive bicycling experiments.
// Copyright (C) 2026  Paulo Sérgio
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package ai

// OllamaChatRequest represents a request to the Ollama chat API.
type OllamaChatRequest struct {
	Model    string                 `json:"model"`
	Messages []OllamaMessage        `json:"messages"`
	Stream   bool                   `json:"stream"`
	Format   interface{}            `json:"format,omitempty"`
	Options  map[string]interface{} `json:"options,omitempty"`
}

// OllamaMessage represents a message in the Ollama chat API.
type OllamaMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// OllamaChatResponse represents a response from the Ollama chat API.
type OllamaChatResponse struct {
	Message OllamaMessage `json:"message"`
	Done    bool          `json:"done"`
}

// OllamaModel represents a model in the Ollama model list.
type OllamaModel struct {
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	ModifiedAt string `json:"modified_at"`
}

// OllamaTagsResponse represents the response from the Ollama tags API.
type OllamaTagsResponse struct {
	Models []OllamaModel `json:"models"`
}

// AIStructuredResponse is the expected JSON structure from the AI model.
type AIStructuredResponse struct {
	Response string         `json:"response"`
	Workout  *AIWorkoutPlan `json:"workout,omitempty"`
}

// AIWorkoutPlan represents a workout plan generated by the AI.
type AIWorkoutPlan struct {
	Name     string             `json:"name"`
	Segments []AIWorkoutSegment `json:"segments"`
}

// AIWorkoutSegment represents a segment in an AI-generated workout.
type AIWorkoutSegment struct {
	Type        string   `json:"type"`
	Duration    int      `json:"duration"`
	Power       *float64 `json:"power,omitempty"`
	PowerLow    *float64 `json:"powerLow,omitempty"`
	PowerHigh   *float64 `json:"powerHigh,omitempty"`
	Repeat      *int     `json:"repeat,omitempty"`
	OnDuration  *int     `json:"onDuration,omitempty"`
	OnPower     *float64 `json:"onPower,omitempty"`
	OffDuration *int     `json:"offDuration,omitempty"`
	OffPower    *float64 `json:"offPower,omitempty"`
}
