// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePowerSimulation(arg1) {
  return window['go']['main']['App']['ChangePowerSimulation'](arg1);
}

export function ChangeWorkoutIntensity(arg1) {
  return window['go']['main']['App']['ChangeWorkoutIntensity'](arg1);
}

export function ConnectHeartRate(arg1) {
  return window['go']['main']['App']['ConnectHeartRate'](arg1);
}

export function ConnectStrava() {
  return window['go']['main']['App']['ConnectStrava']();
}

export function ConnectTrainer(arg1) {
  return window['go']['main']['App']['ConnectTrainer'](arg1);
}

export function ConnectVirtualTrainer() {
  return window['go']['main']['App']['ConnectVirtualTrainer']();
}

export function CreateLocalAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateLocalAccount'](arg1, arg2, arg3, arg4);
}

export function DeleteActivityHistory(arg1) {
  return window['go']['main']['App']['DeleteActivityHistory'](arg1);
}

export function DeleteLocalAccount(arg1) {
  return window['go']['main']['App']['DeleteLocalAccount'](arg1);
}

export function DiscardSession() {
  return window['go']['main']['App']['DiscardSession']();
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function DisconnectHeartRate() {
  return window['go']['main']['App']['DisconnectHeartRate']();
}

export function DisconnectStrava() {
  return window['go']['main']['App']['DisconnectStrava']();
}

export function DisconnectTrainer() {
  return window['go']['main']['App']['DisconnectTrainer']();
}

export function FinishSession() {
  return window['go']['main']['App']['FinishSession']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetActivityDetails(arg1) {
  return window['go']['main']['App']['GetActivityDetails'](arg1);
}

export function GetCareerDashboard() {
  return window['go']['main']['App']['GetCareerDashboard']();
}

export function GetElevationProfile() {
  return window['go']['main']['App']['GetElevationProfile']();
}

export function GetLocalAccounts() {
  return window['go']['main']['App']['GetLocalAccounts']();
}

export function GetMonthlyActivities(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyActivities'](arg1, arg2);
}

export function GetPowerCurve() {
  return window['go']['main']['App']['GetPowerCurve']();
}

export function GetRoutePath() {
  return window['go']['main']['App']['GetRoutePath']();
}

export function GetTotalStats() {
  return window['go']['main']['App']['GetTotalStats']();
}

export function GetUserProfile() {
  return window['go']['main']['App']['GetUserProfile']();
}

export function IsStravaConnected() {
  return window['go']['main']['App']['IsStravaConnected']();
}

export function LoadWorkout() {
  return window['go']['main']['App']['LoadWorkout']();
}

export function OpenFileFolder(arg1) {
  return window['go']['main']['App']['OpenFileFolder'](arg1);
}

export function RepeatWorkout() {
  return window['go']['main']['App']['RepeatWorkout']();
}

export function ResetAppState() {
  return window['go']['main']['App']['ResetAppState']();
}

export function SaveGeneratedGPX(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratedGPX'](arg1, arg2);
}

export function ScanHeartRate() {
  return window['go']['main']['App']['ScanHeartRate']();
}

export function ScanTrainers() {
  return window['go']['main']['App']['ScanTrainers']();
}

export function SelectGPX() {
  return window['go']['main']['App']['SelectGPX']();
}

export function SelectLocalAccount(arg1) {
  return window['go']['main']['App']['SelectLocalAccount'](arg1);
}

export function SelectProfileImage() {
  return window['go']['main']['App']['SelectProfileImage']();
}

export function SetPowerTarget(arg1) {
  return window['go']['main']['App']['SetPowerTarget'](arg1);
}

export function SetTrainerMode(arg1) {
  return window['go']['main']['App']['SetTrainerMode'](arg1);
}

export function StartWorkout() {
  return window['go']['main']['App']['StartWorkout']();
}

export function ToggleAlwaysOnTop(arg1) {
  return window['go']['main']['App']['ToggleAlwaysOnTop'](arg1);
}

export function ToggleSession() {
  return window['go']['main']['App']['ToggleSession']();
}

export function UnloadWorkout() {
  return window['go']['main']['App']['UnloadWorkout']();
}

export function UpdateUserProfile(arg1) {
  return window['go']['main']['App']['UpdateUserProfile'](arg1);
}

export function UploadActivityToStrava(arg1) {
  return window['go']['main']['App']['UploadActivityToStrava'](arg1);
}

export function UploadLastWorkoutToStrava() {
  return window['go']['main']['App']['UploadLastWorkoutToStrava']();
}
