// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePowerSimulation(arg1) {
  return window['go']['main']['App']['ChangePowerSimulation'](arg1);
}

export function ConnectHeartRate() {
  return window['go']['main']['App']['ConnectHeartRate']();
}

export function ConnectTrainer() {
  return window['go']['main']['App']['ConnectTrainer']();
}

export function DiscardSession() {
  return window['go']['main']['App']['DiscardSession']();
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function FinishSession() {
  return window['go']['main']['App']['FinishSession']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetElevationProfile() {
  return window['go']['main']['App']['GetElevationProfile']();
}

export function GetRoutePath() {
  return window['go']['main']['App']['GetRoutePath']();
}

export function GetTotalStats() {
  return window['go']['main']['App']['GetTotalStats']();
}

export function GetUserProfile() {
  return window['go']['main']['App']['GetUserProfile']();
}

export function OpenFileFolder(arg1) {
  return window['go']['main']['App']['OpenFileFolder'](arg1);
}

export function SelectGPX() {
  return window['go']['main']['App']['SelectGPX']();
}

export function ToggleAlwaysOnTop(arg1) {
  return window['go']['main']['App']['ToggleAlwaysOnTop'](arg1);
}

export function ToggleSession() {
  return window['go']['main']['App']['ToggleSession']();
}

export function UpdateUserProfile(arg1) {
  return window['go']['main']['App']['UpdateUserProfile'](arg1);
}
