// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {storage} from '../models';
import {main} from '../models';

export function ChangePowerSimulation(arg1:number):Promise<number>;

export function ConnectHeartRate():Promise<string>;

export function ConnectTrainer():Promise<string>;

export function DiscardSession():Promise<string>;

export function DisconnectDevice():Promise<string>;

export function FinishSession():Promise<string>;

export function GetActivities():Promise<Array<domain.Activity>>;

export function GetElevationProfile():Promise<Array<number>>;

export function GetMonthlyActivities(arg1:number,arg2:number):Promise<Array<domain.Activity>>;

export function GetPowerCurve():Promise<Array<storage.PowerRecord>>;

export function GetRoutePath():Promise<Array<domain.RoutePoint>>;

export function GetTotalStats():Promise<Record<string, number>>;

export function GetUserProfile():Promise<domain.UserProfile>;

export function OpenFileFolder(arg1:string):Promise<void>;

export function SaveGeneratedGPX(arg1:string,arg2:Array<main.ExportPoint>):Promise<string>;

export function SelectGPX():Promise<string>;

export function SelectProfileImage():Promise<string>;

export function SetPowerTarget(arg1:number):Promise<void>;

export function SetTrainerMode(arg1:string):Promise<void>;

export function ToggleAlwaysOnTop(arg1:boolean):Promise<void>;

export function ToggleSession():Promise<string>;

export function UpdateUserProfile(arg1:domain.UserProfile):Promise<string>;
