// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {domain} from '../models';
import {fit} from '../models';
import {storage} from '../models';

export function ChangePowerSimulation(arg1:number):Promise<number>;

export function ChangeWorkoutIntensity(arg1:number):Promise<number>;

export function ConnectHeartRate(arg1:string):Promise<string>;

export function ConnectStrava():Promise<string>;

export function ConnectTrainer(arg1:string):Promise<string>;

export function ConnectVirtualTrainer():Promise<string>;

export function CreateLocalAccount(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function DeleteActivityHistory(arg1:number):Promise<void>;

export function DiscardSession():Promise<string>;

export function DisconnectDevice():Promise<string>;

export function DisconnectHeartRate():Promise<string>;

export function DisconnectStrava():Promise<void>;

export function DisconnectTrainer():Promise<string>;

export function FinishSession():Promise<main.SessionSummary>;

export function GetActivities():Promise<Array<domain.Activity>>;

export function GetActivityDetails(arg1:string):Promise<fit.ActivityDetails>;

export function GetCareerDashboard():Promise<main.CareerDashboard>;

export function GetElevationProfile():Promise<Array<number>>;

export function GetLocalAccounts():Promise<Array<storage.ProfileSummary>>;

export function GetMonthlyActivities(arg1:number,arg2:number):Promise<Array<domain.Activity>>;

export function GetPowerCurve():Promise<Array<storage.PowerRecord>>;

export function GetRoutePath():Promise<Array<domain.RoutePoint>>;

export function GetTotalStats():Promise<Record<string, number>>;

export function GetUserProfile():Promise<domain.UserProfile>;

export function IsStravaConnected():Promise<boolean>;

export function LoadWorkout():Promise<string>;

export function OpenFileFolder(arg1:string):Promise<void>;

export function ResetAppState():Promise<void>;

export function SaveGeneratedGPX(arg1:string,arg2:Array<main.ExportPoint>):Promise<string>;

export function ScanHeartRate():Promise<Array<domain.BLEDevice>>;

export function ScanTrainers():Promise<Array<domain.BLEDevice>>;

export function SelectGPX():Promise<string>;

export function SelectLocalAccount(arg1:string):Promise<string>;

export function SelectProfileImage():Promise<string>;

export function SetPowerTarget(arg1:number):Promise<void>;

export function SetTrainerMode(arg1:string):Promise<void>;

export function StartWorkout():Promise<void>;

export function ToggleAlwaysOnTop(arg1:boolean):Promise<void>;

export function ToggleSession():Promise<string>;

export function UnloadWorkout():Promise<void>;

export function UpdateUserProfile(arg1:domain.UserProfile):Promise<string>;

export function UploadLastWorkoutToStrava():Promise<string>;
