// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ChangePowerSimulation(arg1:number):Promise<number>;

export function ConnectHeartRate():Promise<string>;

export function ConnectTrainer():Promise<string>;

export function DiscardSession():Promise<string>;

export function DisconnectDevice():Promise<string>;

export function FinishSession():Promise<string>;

export function GetElevationProfile():Promise<Array<number>>;

export function GetRoutePath():Promise<Array<domain.RoutePoint>>;

export function SelectGPX():Promise<string>;

export function ToggleAlwaysOnTop(arg1:boolean):Promise<void>;

export function ToggleSession():Promise<string>;
