// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePowerSimulation(arg1) {
  return window['go']['main']['App']['ChangePowerSimulation'](arg1);
}

export function ChangeWorkoutIntensity(arg1) {
  return window['go']['main']['App']['ChangeWorkoutIntensity'](arg1);
}

export function ConnectHeartRate() {
  return window['go']['main']['App']['ConnectHeartRate']();
}

export function ConnectTrainer() {
  return window['go']['main']['App']['ConnectTrainer']();
}

export function DiscardSession() {
  return window['go']['main']['App']['DiscardSession']();
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function FinishSession() {
  return window['go']['main']['App']['FinishSession']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetElevationProfile() {
  return window['go']['main']['App']['GetElevationProfile']();
}

export function GetMonthlyActivities(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyActivities'](arg1, arg2);
}

export function GetPowerCurve() {
  return window['go']['main']['App']['GetPowerCurve']();
}

export function GetRoutePath() {
  return window['go']['main']['App']['GetRoutePath']();
}

export function GetTotalStats() {
  return window['go']['main']['App']['GetTotalStats']();
}

export function GetUserProfile() {
  return window['go']['main']['App']['GetUserProfile']();
}

export function LoadWorkout() {
  return window['go']['main']['App']['LoadWorkout']();
}

export function OpenFileFolder(arg1) {
  return window['go']['main']['App']['OpenFileFolder'](arg1);
}

export function SaveGeneratedGPX(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratedGPX'](arg1, arg2);
}

export function SelectGPX() {
  return window['go']['main']['App']['SelectGPX']();
}

export function SelectProfileImage() {
  return window['go']['main']['App']['SelectProfileImage']();
}

export function SetPowerTarget(arg1) {
  return window['go']['main']['App']['SetPowerTarget'](arg1);
}

export function SetTrainerMode(arg1) {
  return window['go']['main']['App']['SetTrainerMode'](arg1);
}

export function StartWorkout() {
  return window['go']['main']['App']['StartWorkout']();
}

export function ToggleAlwaysOnTop(arg1) {
  return window['go']['main']['App']['ToggleAlwaysOnTop'](arg1);
}

export function ToggleSession() {
  return window['go']['main']['App']['ToggleSession']();
}

export function UnloadWorkout() {
  return window['go']['main']['App']['UnloadWorkout']();
}

export function UpdateUserProfile(arg1) {
  return window['go']['main']['App']['UpdateUserProfile'](arg1);
}
